apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-user-service
  template:
    metadata:
      labels:
        app: mongo-user-service
    spec:
      containers:
        - name: mongo-user-service
          image: mongo:noble
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-user-service-storage
              mountPath: /data/db
      volumes:
        - name: mongo-user-service-storage
          persistentVolumeClaim:
            claimName: mongo-user-service-pvc
